# Generated by Django 4.2.13 on 2024-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.IntegerField()),
                ('blue', models.BooleanField()),
                ('clock_speed', models.FloatField()),
                ('dual_sim', models.BooleanField()),
                ('fc', models.IntegerField()),
                ('four_g', models.BooleanField()),
                ('int_memory', models.IntegerField()),
                ('m_dep', models.FloatField()),
                ('mobile_wt', models.IntegerField()),
                ('n_cores', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('px_height', models.IntegerField()),
                ('px_width', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('sc_h', models.IntegerField()),
                ('sc_w', models.IntegerField()),
                ('talk_time', models.IntegerField()),
                ('three_g', models.BooleanField()),
                ('touch_screen', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('price_range', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
